site_name: 7 Days of Python

theme:
  icon:
    logo: simple/python

  favicon: images/python.ico

  name: material
  features:
    - header.autohide
    - navigation.footer
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to system preference

# Repository
repo_name: rishabkumar7/7DaysOfPython
repo_url: https://github.com/rishabkumar7/7DaysOfPython

font:
    text: Roboto
    code: Roboto Mono

copyright: Copyright &copy; 2024 Rishab Kumar

#syntax highlighting
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

#extras
extra:
  analytics:
    provider: google
    property: G-VB7ZE3N6CE
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/rishabincloud
      name: Rishab on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/rishabkumar7
